sudo: required
language: node_js
node_js:
  - "8.9"
dist: trusty
cache: yarn
branches:
  only:
    - master
notifications:
  email: false
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - npm run ci
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/browser
  github_token: $GH_TOKEN
  on:
    branch: master
